version: '3'
services:

  web:
    container_name: web
    image: "myselectshop-docker"
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: myselectshop-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: